### ISSUE TITLE
Limit search results

### ISSUE THREAD

**Issue by uponatime2019** [tomaspavlic/opensubtitles-api#1]
Hello, how to search with more results? I tried with many keywords but just return max 5 results

**Comment by tomaspavlic** [comment]
Hi @uponatime2019, you have to register your own agent with opensubtitles.org. The TemporaryUserAgent has limitation for testing and developing purposes.

https://trac.opensubtitles.org/projects/opensubtitles/wiki/DevReadFirst
`ONLY for testing and developing purposes you can use special user agent "TemporaryUserAgent". Never use this UA as default/public/in production code, we periodically change this and your APP will stop work! Also don't abuse usage of this test user agent. TemporaryUserAgent have limit 5 search results only, so you need to register your own User Agent, TemporaryUserAgent is used just for developing your code in meantime, until you register your own User Agent.`
